### ISSUE TITLE
Support retrieving stats by game ID

### ISSUE THREAD

**Issue by kparal** [ScrappyCocco/HowLongToBeat-PythonAPI#1]
This library currently only supports searching by game title. However, in some cases, I already know the game ID (for example when I already searched for this title and just want to update the information). If I know the ID, I would like to retrieve the game stats directly, instead of searching for the title again and having to deal with other titles that might be named the same way or similarly. Can you please support something like this?
```
result = HowLongToBeat().game_id('62935')
```
That would involve parsing this web page:
https://howlongtobeat.com/game.php?id=62935

Thanks!

**Comment by ScrappyCocco** [comment]
Thanks for the request and for using my lib!
Will do this as soon as possible and i'll update you!

**Comment by ScrappyCocco** [comment]
Done, the new version [0.1.7](https://pypi.org/project/howlongtobeatpy/) include the search by id
You can read [in the readme](https://github.com/ScrappyCocco/HowLongToBeat-PythonAPI#alternative-search-by-id) how it works
Thanks for the issue, write to me if you need anything else
Best regards

**Comment by kparal** [comment]
Thanks!
