### ISSUE TITLE
Setup.py fake_useragent==0.1.11

### ISSUE THREAD

**Issue by D-Militao** [ScrappyCocco/HowLongToBeat-PythonAPI#18]
When I installed the package it also installed `fake_useragent==0.1.11`.
Unfortunately, I kept on getting the following error:
```fake_useragent.errors.FakeUserAgentError: Maximum amount of retries reached```
Updating `fake_useragent` to the latest version (1.1.0) solved this issue for me and I haven't had any other issues since.

**Comment by ScrappyCocco** [comment]
Fixed in https://github.com/ScrappyCocco/HowLongToBeat-PythonAPI/releases/tag/1.0.3 ! Thanks!
