### ISSUE TITLE
Searching only returns 1 game when the web search returns 6

### ISSUE THREAD

**Issue by kparal** [ScrappyCocco/HowLongToBeat-PythonAPI#3]
When I search for "Grip" on HLTB web, I get 6 results:
```
GRIP: Combat Racing 
Hot Shots Tennis: Get a Grip 
GripShift 
Iron Grip: Warlord 
Griptape Backbone 
Iron Grip: Marauders 
```
However, using the API, I get just one result:
```
> from howlongtobeatpy import HowLongToBeat, HowLongToBeatEntry 
> results = HowLongToBeat().search('Grip')                                                                        
> print(len(results))
1
> print(results[0].game_name)
GripShift
```
Am I doing something wrong?

howlongtobeatpy-0.1.10

**Comment by ScrappyCocco** [comment]
Hello again!
No you're not doing anything wrong, i think the cause is this line here:

https://github.com/ScrappyCocco/HowLongToBeat-PythonAPI/blob/2c3cb9e748080c51e142a51bb6c211a82d8991af/howlongtobeatpy/howlongtobeatpy/HTMLResultParser.py#L83

If the name is too different the parser doesn't consider it, but the request return all the 6 games you found!
If you really need all the results i guess i can add a parameter, such as a `autoFilerElements` that could be `True` by default, so you can turn it off when needed

Let me know why do you need all the results/if you want the parameter ^^

**Comment by kparal** [comment]
Ah, I thought `similarity` was actually returned by HLTB and now I see it's a score coming from your library. I can imagine two approaches to let me configure this behavior:
1. True/False argument to enable/disable filtering of returned results (as you suggested). It would be nice to have the cutoff threshold (`0.4`) documented as well.
2. Option to set the minimum similarity threshold myself (any value between 0 and 1). Setting it to 0 would be the same as disabling filtering.

I don't really have a preference. In my use case, I'll probably disable the filtering completely. Thanks in advance.

**Comment by ScrappyCocco** [comment]
Yeah i will probably do it as the second way, tomorrow or anyway this week
Thank you for your feedback, i will also specify it in the readme

**Comment by ScrappyCocco** [comment]
Thank you, it's done in 0.1.11
You can see the readme that explain it [here](https://github.com/ScrappyCocco/HowLongToBeat-PythonAPI#results-auto-filter).
Let me know if you need anything else ^^ have a nice week

**Comment by kparal** [comment]
This seems to have caused a side effect where if you search for a game that is not found, you get a `HowLongToBeatEntry` with all `None` values. But only if you specify `input_minimum_similarity=0`.

```
from howlongtobeatpy import HowLongToBeat, HowLongToBeatEntry
results = HowLongToBeat().search('Thief: Gold')
print(len(results))
> 0
results = HowLongToBeat(input_minimum_similarity=0.4).search('Thief: Gold')
print(len(results))
> 0
results = HowLongToBeat(input_minimum_similarity=0).search('Thief: Gold')
print(len(results))
> 1
print(vars(results[0]))
> {'game_id': -1,
 'game_name': None,
 'game_image_url': None,
 'game_web_link': None,
 'gameplay_main': -1,
 'gameplay_main_unit': None,
 'gameplay_main_label': None,
 'gameplay_main_extra': -1,
 'gameplay_main_extra_unit': None,
 'gameplay_main_extra_label': None,
 'gameplay_completionist': -1,
 'gameplay_completionist_unit': None,
 'gameplay_completionist_label': None,
 'similarity': 0}
```

**Comment by ScrappyCocco** [comment]
Oh damn, please open an issue with this code you just gave to me and i'll fix it today
Sorry
