### ISSUE TITLE
[BUG] Can't fetch the API key

### ISSUE THREAD

**Issue by Eniterusx** [ScrappyCocco/HowLongToBeat-PythonAPI#30]
I have been using the API recently, but looks like it just broke?

```
File "\Lib\site-packages\howlongtobeatpy\HTMLRequests.py", line 102, in send_web_request
search_url_with_key = HTMLRequests.SEARCH_URL + "/" + api_key_result
                      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~
TypeError: can only concatenate str (not "NoneType") to str
```

It has problems with fetching the api_key. Did they change the API yet again?
The request to howlongtobeat works perfectly, but it looks like the api key is no longer present in the html content.

**Comment by elogicuk** [comment]
00:55:03.267         [SYSTEM] Fetching HLTB data for game: Black Myth: Wukong
00:55:21.198 WARNING [SYSTEM] HLTB search attempt 1 failed: can only concatenate str (not "NoneType") to str


yeah its broken sadly

**Comment by ScrappyCocco** [comment]
Thank you for the support
Fixed in [https://github.com/ScrappyCocco/HowLongToBeat-PythonAPI/releases/tag/1.0.10](https://github.com/ScrappyCocco/HowLongToBeat-PythonAPI/releases/tag/1.0.10)

**Comment by nullseade** [comment]
Hi

it looks they've changed the code again, current javascript to scrape for me was
"/_next/static/chunks/pages/_app-858f64c972a7c8b1.js"
and `users:` tag there does not have `id:` field any more, just {sortCategory:X}

or is it working fine for you?

**Comment by nullseade** [comment]
okay, it looks to me they went back to concat, current fetch in that .js I gave above is 
`fetch("/api/search/".concat("7b0f03b2").concat("54cc3099")` 
so combining these :alnum: regex matches gives tha API key, 


this following is not general advice, this is how it works for me
search needs to modified back to PATH+APIKEY `search_url_with_key = HTMLRequests.SEARCH_URL + "/" + api_key_result`,

**Comment by ScrappyCocco** [comment]
@nullseade @godver3 see #31 for updates
