### ISSUE TITLE
[BUG] Search URL has changed

### ISSUE THREAD

**Issue by xavdid** [ScrappyCocco/HowLongToBeat-PythonAPI#39]
**Describe the bug**

I'm getting 500 errors from this line: https://github.com/ScrappyCocco/HowLongToBeat-PythonAPI/blob/6be69cd7228cad0694948a8cb85168b63607646b/howlongtobeatpy/howlongtobeatpy/HTMLRequests.py#L149

because `api_key_result` is `None` and `None + ''` is a type error. 

It's because the search url is now `https://howlongtobeat.com/api/lookup/<random portion>`. So I'd update the regex to look for `(find|lookup)` in the js script and update the `SEARCH_URL` accordingly

**HLTB API Version**

1.0.14

**Comment by rarDevelopment** [comment]
Just submitted this PR a few minutes ago actually, I think this should fix it.
https://github.com/ScrappyCocco/HowLongToBeat-PythonAPI/pull/38

**Comment by ScrappyCocco** [comment]
Fixed in [1.0.15](https://github.com/ScrappyCocco/HowLongToBeat-PythonAPI/releases/tag/1.0.15)
