### ISSUE TITLE
please support search modifiers to include/isolate DLCs

### ISSUE THREAD

**Issue by kparal** [ScrappyCocco/HowLongToBeat-PythonAPI#6]
howlongtobeat.com search form changed and now it doesn't show DLCs in search results, unless you open Search Options and change Modifiers to Include (or Isolate) DLC.

You can test this by searching e.g. for "Hearts of Stone". You'll see no results until you include DLCs in search options.

Please support search modifiers in `HowLongToBeat.search()` and `async_search()` methods.

For example:
```
def search(self, game_name: str, dlc: str = None):
:param dlc: possible values are None to not modify search options, 'include' to also include DLC names in search results, and 'isolate' to search in DLC names only
```

Thank you!

**Comment by ScrappyCocco** [comment]
Thanks for telling, I identified the parameter and will update you as soon as possible

**Comment by ScrappyCocco** [comment]
This should work as expected, see tests in case you're not sure about how to use it
Tell me if you need anything else,
have a good week ^^

**Comment by kparal** [comment]
It works perfectly. Thanks a lot.
