### ISSUE TITLE
Case-insensitive similarity

### ISSUE THREAD

**Issue by Kononkov1998** [ScrappyCocco/HowLongToBeat-PythonAPI#7]
Hello! 
Sometimes the name of the game in some source (e. g. Steam) and on HLTB completely coincides, not counting the case, but the similarity is very low. For example, game RED HOT VENGEANCE has only 0.3 similarity.

It would be great if you can add case insensitive search capability. 
It might look something like this:
`HowLongToBeat(0.9).search("game_name", case_sensitive = False)`

Thank you!

**Comment by ScrappyCocco** [comment]
Thanks for the feedback, will do it now

**Comment by Kononkov1998** [comment]
It works great. Thanks!
